// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)
import NestedRondoController from "./nested_rondo_controller"
application.register("nested-rondo", NestedRondoController)
import ToggleFieldController from "./toggle_field_controller"
application.register("toggle-field", ToggleFieldController)
import ProviderSelectionController from "./provider_selection_controller"
application.register("provider-selection", ProviderSelectionController)
import VatApplicationController from "./vat_application_controller"
application.register("vat-application", VatApplicationController)
import ToggleUnitController from "./toggle_unit_controller"
application.register("toggle-unit", ToggleUnitController)
import InteractiveButtonController from "./interactive_button_controller"
application.register("interactive-button", InteractiveButtonController)
